[env:esp32dev]
platform = espressif32@6.5.0
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv

lib_deps =
  https://github.com/pschatzmann/arduino-audio-tools.git
  https://github.com/pschatzmann/arduino-libhelix.git
  olikraus/U8g2@^2.35.9
  tzapu/WiFiManager@^2.0.17
  bblanchon/ArduinoJson@^7.0.4
  links2004/WebSockets@^2.4.1

; ---- PERFORMANCE OPTIMIZATIONS ----
board_build.f_cpu = 240000000L      ; 240 MHz CPU Max
board_build.f_flash = 80000000L     ; 80 MHz Flash Max
board_build.flash_mode = qio        ; Quad I/O Flash reads
build_flags = 
  -O2                               ; Optimize speed
  -DCORE_DEBUG_LEVEL=3              ; Info level debug logs
  -DsetConnectionTimeout=setTimeout ; Resolve ESP32 core WiFiClient setConnectionTimeout missing error

